pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                withMaven(traceability: true){}
                sh 'mvn -f app/ -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                withMaven(traceability: true){}
                sh 'mvn -f app/ test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}
