server:
  port: 2930

database:
  host: localhost
  port: 15432
  schema: blog

app:
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.schema}
    username: postgres
    password: password

spring:
  rabbitmq:
    password: rabbitmq
    username: rabbitmq
  application:
    name: university
#  datasource:
#    url: jdbc:postgresql://${database.host}:${database.port}/${database.schema}
#    username: postgres
#    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false


logging:
  pattern:
    level:
      org.springframework.orm.jpa: TRACE
      org.springframework.transaction: TRACE