version: '2.4'

services:
  db-university:
    restart: on-failure
    image: "postgres:14.1"
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=university
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  db-university-test:
    restart: on-failure
    image: "postgres:14.1"
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_DB=university
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password


  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
